config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :comments

  resources :sessions, only: [:new, :create]

  resources :images

  root :to => 'images#index'

  resources :sessions, :only => [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'

end

app/models/image.rb
class Image < ActiveRecord::Base
	has_many :comments, dependent: :destroy
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @comments = Comment.where(:image_id => params[:id])
    @images = Image.all
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new #(image_params)

    #if testing local:
   # @information = Cloudinary::Uploader.upload('/home/joe/bearded-ninja-backend/app/assets/images/kuva4.jpg')
    
    @information = Cloudinary::Uploader.upload(params[:file])
    ind = 0
    @information.each do |i|
       if ind == 11
           @url = i[1]
       end  
    ind = ind + 1
    end
    @image.imageUrl = @url
    begin
       @generatedID = "BN-" + create_10_random_numbers() + @image.id.to_s
    end while Image.where(:generated_id => @generatedID).first != nil
    @image.generated_id = @generatedID
    @image.name = params[:imgName]
    @image.tags = params[:imgTags]
    @image.mature = params[:imgMature]
    @image.views = 0

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
     # params.require(:image).permit(:file)
    end

    def create_10_random_numbers
        return "" + rand(1..9).to_s + rand(1..9).to_s + rand(1..9).to_s + rand(1..9).to_s + rand(1..9).to_s + rand(1..9).to_s + rand(1..9).to_s + rand(1..9).to_s + rand(1..9).to_s + rand(1..9).to_s
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :imageUrl %><br>
    <%= f.text_field :imageUrl %>
  </div>
  <div class="field">
    <%= f.label :views %><br>
    <%= f.number_field :views %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Imageurl</th>
      <th>Views</th>
      <th>Points</th>
      <th>Tags</th>
      <th>Mature</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= link_to image.name, image %></td>
        <td><%= link_to image.imageUrl, image.imageUrl %></td>
        <td><%= image.views %></td>
        <td><%= image.points %></td>
        <td><%= image.tags %></td>
        <td><%= image.mature %></td>
        <td><%= image.created_at %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<b><%= link_to 'Show all comments', comments_path %></b>

<br>
<br>

<b><%= link_to 'New Image', new_image_path %></b>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>


<h1>Name: <%= @image.name %></h1>

<p>
  <strong>Imageurl: </strong> <%= link_to @image.imageUrl, @image.imageUrl %>
</p>

<p>
  <strong>Views:</strong>
  <%= @image.views %>
</p>

<h2><b>Comments:</b></h2>
<% @comments.each do |comment| %>
   <b>Name: </b><%= comment.name %>
   <b>Comment: </b><%= comment.comment %>
</br>
<% end %>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>